# Generated by Django 4.2.24 on 2025-09-16 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
